Repository udecode/plate, pull requests merged in 2020-05, with the labels that each got.

#120 make prefix and trigger configurable for the mentions plugin
  packages/slate-plugins/src/__tests__/elements/mention/default-prefix.spec.tsx
  packages/slate-plugins/src/common/utils/escapeRegexp.ts
  packages/slate-plugins/src/common/utils/index.ts
  packages/slate-plugins/src/elements/mention/components/MentionElement.tsx
  packages/slate-plugins/src/elements/mention/components/MentionSelect.tsx
  packages/slate-plugins/src/elements/mention/transforms/insertMention.ts
  packages/slate-plugins/src/elements/mention/types.ts
  packages/slate-plugins/src/elements/mention/useMention.tsx
  stories/config/data.ts
  stories/config/initialValues.ts
  stories/element/inline-void/mention.stories.tsx
  stories/examples/playground.stories.tsx
Labels: BREAKING CHANGE, cleanup, configuration, plugin:common, plugin:mention

#129 fix(deserializeMd): fix export + separate utils
  packages/slate-plugins/src/deserializers/deserialize-md/index.ts
  packages/slate-plugins/src/deserializers/deserialize-md/utils/filterBreakLines.ts
  packages/slate-plugins/src/deserializers/deserialize-md/utils/index.ts
  packages/slate-plugins/src/deserializers/deserialize-md/withDeserializeMd.ts
Labels: bug, cleanup, plugin:deserializer-md

#143 add removed arbitrary fields for mention data
  packages/slate-plugins/src/__tests__/elements/mention/useMention/default.spec.tsx
  packages/slate-plugins/src/elements/mention/types.ts
Labels: patch, plugin:mention

#144 Render paragraph as <p> tag
  packages/slate-plugins/src/elements/paragraph/renderElementParagraph.ts
Labels: fix

#145 Use H tags for headings
  packages/slate-plugins/src/elements/heading/components/HeadingElements.tsx
Labels: fix

#146 Add strikethrough class
  packages/slate-plugins/src/marks/strikethrough/renderLeafStrikethrough.tsx
Labels: fix

#124 Serialize to HTML
  README.md
  packages/slate-plugins/src/__tests__/serializers/serialize-html/htmlSerialize.spec.ts
  packages/slate-plugins/src/serializers/index.ts
  packages/slate-plugins/src/serializers/serialize-html/htmlSerialize.ts
  packages/slate-plugins/src/serializers/serialize-html/index.ts
Labels: documentation, plugin:serialize-html

#155 Export serializers
  packages/slate-plugins/src/index.ts
Labels: fix

#159 Fix html serialization issues
  packages/slate-plugins/src/__tests__/serializers/serialize-html/htmlSerialize.spec.ts
  packages/slate-plugins/src/serializers/serialize-html/htmlSerialize.ts
Labels: fix

#164 v0.58.14
  .github/workflows/publish.yml
Labels: release
