Repository udecode/plate, pull requests merged in 2023-09, with the labels that each got.

#2594 Fix column deletion early return
  .changeset/nine-singers-change.md
  packages/table/src/queries/isTableBorderHidden.spec.tsx
  packages/table/src/transforms/deleteColumn.spec.tsx
  packages/table/src/transforms/deleteColumn.ts
Labels: small

#2595 Version Packages
  .changeset/nine-singers-change.md
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializer-csv/CHANGELOG.md
  packages/serializer-csv/package.json
  packages/serializer-docx/CHANGELOG.md
  packages/serializer-docx/package.json
  packages/table/CHANGELOG.md
  packages/table/package.json
Labels: small

#2593 UI #4.1
  .changeset/rotten-cobras-hang.md
  apps/www/content/docs/components/changelog.mdx
  apps/www/public/registry/styles/default/caption.json
  apps/www/public/registry/styles/default/floating-toolbar.json
  apps/www/public/registry/styles/default/image-element.json
  apps/www/public/registry/styles/default/link-floating-toolbar.json
  apps/www/public/registry/styles/default/media-embed-element.json
  apps/www/src/registry/default/plate-ui/caption.tsx
  apps/www/src/registry/default/plate-ui/image-element.tsx
  apps/www/src/registry/default/plate-ui/link-floating-toolbar.tsx
  apps/www/src/registry/default/plate-ui/media-embed-element.tsx
  packages/plate-utils/src/utils/createPrimitiveComponent.tsx
  templates/plate-playground-template/.eslintrc.js
  yarn.lock
Labels: large

#2613 Use H2s in issue template
  .github/ISSUE_TEMPLATE/bug.md
Labels: small

#2614 Do not deserialize `break-word` as code or kbd
  .changeset/tough-bottles-brake.md
  packages/basic-marks/src/createCodePlugin.ts
  packages/kbd/src/createKbdPlugin.ts
Labels: small

#2616 Version Packages
  .changeset/tough-bottles-brake.md
  packages/basic-marks/CHANGELOG.md
  packages/basic-marks/package.json
  packages/kbd/CHANGELOG.md
  packages/kbd/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
Labels: small

#2597 Fix delete forward list for items with multiple children
  .changeset/spicy-birds-accept.md
  packages/list/src/deleteBackwardList.spec.tsx
  packages/list/src/deleteBackwardList.ts
  packages/list/src/deleteForwardList.spec.tsx
  packages/list/src/deleteForwardList.ts
  packages/list/src/withList.ts
Labels: medium, 💰 Rewarded

#2618 Fix: line height state
  .changeset/wild-cups-heal.md
  packages/line-height/src/hooks/useLineHeightDropdownMenu.ts
Labels: small

#2617 Version Packages
  .changeset/spicy-birds-accept.md
  .changeset/wild-cups-heal.md
  packages/indent-list/CHANGELOG.md
  packages/indent-list/package.json
  packages/line-height/CHANGELOG.md
  packages/line-height/package.json
  packages/list/CHANGELOG.md
  packages/list/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializer-docx/CHANGELOG.md
  packages/serializer-docx/package.json
  packages/serializer-md/CHANGELOG.md
  packages/serializer-md/package.json
Labels: small

#2587 Print view fix
  apps/www/src/components/plate-ui/playground-floating-toolbar-buttons.tsx
  apps/www/src/registry/default/plate-ui/image-element.tsx
  apps/www/src/registry/default/plate-ui/link-floating-toolbar.tsx
  apps/www/src/registry/default/plate-ui/media-popover.tsx
  apps/www/src/registry/default/plate-ui/table-element.tsx
  templates/plate-playground-template/src/components/plate-ui/media-popover.tsx
Labels: small

#2620 Version Packages
  .changeset/brown-onions-warn.md
  packages/mention/CHANGELOG.md
  packages/mention/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
Labels: small

#2622 Ensure the return type of `unhangRange` matches the argument type
  .changeset/slow-cats-thank.md
  packages/slate/src/interfaces/editor/unhangRange.ts
Labels: small

#2624 Add jsx element for nli element
  .changeset/wet-ties-do.md
  packages/test-utils/src/jsx.ts
Labels: small

#2625 Version Packages
  .changeset/wet-ties-do.md
  packages/test-utils/CHANGELOG.md
  packages/test-utils/package.json
Labels: small

#2634 New component: Editor
  apps/www/content/docs/components/changelog.mdx
  apps/www/content/docs/components/cloud.mdx
  apps/www/content/docs/components/editor.mdx
  apps/www/content/docs/getting-started.mdx
  apps/www/public/registry/index.json
  apps/www/public/registry/styles/default/editor.json
  apps/www/public/registry/themes.css
  apps/www/src/__registry__/index.tsx
  apps/www/src/app/_components/installation-tab.tsx
  apps/www/src/config/customizer-components.ts
  apps/www/src/config/customizer-items.ts
  apps/www/src/config/docs.ts
  apps/www/src/lib/plate/demo/editableProps.ts
  apps/www/src/registry/default/example/basic-editor-handler-demo.tsx
  apps/www/src/registry/default/example/basic-editor-styling-demo.tsx
  apps/www/src/registry/default/example/basic-editor-value-demo.tsx
  apps/www/src/registry/default/example/basic-plugins-components-demo.tsx
  apps/www/src/registry/default/example/basic-plugins-default-demo.tsx
  apps/www/src/registry/default/example/cloud-demo.tsx
  apps/www/src/registry/default/example/editable-voids-demo.tsx
  apps/www/src/registry/default/example/editor-button.tsx
  apps/www/src/registry/default/example/editor-default.tsx
  apps/www/src/registry/default/example/editor-disabled.tsx
  apps/www/src/registry/default/example/editor-form.tsx
  apps/www/src/registry/default/example/editor-ghost.tsx
  apps/www/src/registry/default/example/editor-label.tsx
  apps/www/src/registry/default/example/editor-text.tsx
  apps/www/src/registry/default/example/find-replace-demo.tsx
  apps/www/src/registry/default/example/hundreds-blocks-demo.tsx
  apps/www/src/registry/default/example/hundreds-editors-demo.tsx
  apps/www/src/registry/default/example/iframe-demo.tsx
  apps/www/src/registry/default/example/multiple-editors-demo.tsx
  apps/www/src/registry/default/example/playground-demo.tsx
  apps/www/src/registry/default/example/preview-md-demo.tsx
  apps/www/src/registry/default/plate-ui/editor.tsx
  apps/www/src/registry/registry.ts
  apps/www/src/registry/themes.ts
  apps/www/src/styles/globals.css
  templates/plate-playground-template/package.json
  templates/plate-playground-template/pnpm-lock.yaml
  templates/plate-playground-template/src/components/plate-editor.tsx
  templates/plate-playground-template/src/components/plate-ui/button.tsx
  templates/plate-playground-template/src/components/plate-ui/code-block-element.css
  templates/plate-playground-template/src/components/plate-ui/editor.tsx
  templates/plate-playground-template/src/components/plate-ui/fixed-toolbar-buttons.tsx
  templates/plate-playground-template/src/components/plate-ui/floating-toolbar-buttons.tsx
  templates/plate-playground-template/src/components/plate-ui/mode-dropdown-menu.tsx
  templates/plate-template/package.json
  templates/plate-template/pnpm-lock.yaml
  templates/plate-template/src/app/layout.tsx
  templates/plate-template/src/app/page.tsx
  templates/plate-template/src/components/plate-editor.tsx
  templates/plate-template/src/components/plate-ui/editor.tsx
Labels: large

#2635 Plate id prop string
  .changeset/two-avocados-hear.md
  apps/www/content/docs/api/core/plate.mdx
  apps/www/src/lib/plate/demo/plugins/emojiPlugin.ts
  packages/core/src/components/Plate.spec.tsx
  packages/core/src/stores/plate/createPlateStore.ts
  packages/core/src/types/slate-react/TEditableProps.ts
  templates/plate-playground-template/src/lib/plate/plate-plugins.ts
Labels: small

#2639 🐛 fix floating link
  .changeset/neat-pillows-prove.md
  apps/www/src/components/command-menu.tsx
  apps/www/src/config/docs.ts
  apps/www/src/registry/default/example/playground-demo.tsx
  packages/core/src/components/EditorRefEffect.tsx
Labels: small

#2642 Sync shadcn
  .changeset/twelve-cars-drop.md
  apps/www/content/docs/components/cli.mdx
  apps/www/content/docs/components/dark-mode/next.mdx
  packages/cli/src/commands/add.ts
  packages/cli/src/utils/transformers/transform-css-vars.ts
  packages/cli/test/utils/__snapshots__/transform-css-vars.test.ts.snap
  packages/cli/test/utils/apply-color-mapping.test.ts
  packages/cli/test/utils/transform-css-vars.test.ts
Labels: medium

#2643 Version Packages
  .changeset/twelve-cars-drop.md
  packages/cli/CHANGELOG.md
  packages/cli/package.json
Labels: small

#2648 Version Packages
  .changeset/rare-cycles-destroy.md
  packages/cli/CHANGELOG.md
  packages/cli/package.json
Labels: small
