Repository udecode/plate, pull requests merged in 2023-07, with the labels that each got.

#2459 Debug/serialize html/expected drag drop context
  docs/docs/plugins/serializing-html.mdx
  docs/docs/sandpack/files/serializing-html/code-deserializeHtmlValue.tsx
  docs/docs/sandpack/plate-versions.ts
  examples/src/serializing-html/deserializeHtmlValue.tsx
  yarn.lock
Labels: large, waiting-for-review

#2462 Version Packages
  .changeset/thick-meals-melt.md
  packages/headless/CHANGELOG.md
  packages/headless/package.json
  packages/nodes/table/CHANGELOG.md
  packages/nodes/table/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializers/csv/CHANGELOG.md
  packages/serializers/csv/package.json
  packages/serializers/docx/CHANGELOG.md
  packages/serializers/docx/package.json
  packages/ui/nodes/table/CHANGELOG.md
  packages/ui/nodes/table/package.json
  packages/ui/plate/CHANGELOG.md
  packages/ui/plate/package.json
Labels: small, waiting-for-review

#2445 Use Radix Popover instead of Floating UI where possible
  apps/www/public/registry/index.json
  apps/www/public/registry/styles/default/combobox.json
  apps/www/public/registry/styles/default/emoji-dropdown-menu.json
  apps/www/public/registry/styles/default/image-element.json
  apps/www/public/registry/styles/default/media-embed-element.json
  apps/www/public/registry/styles/default/media-popover.json
  apps/www/public/registry/styles/default/popover.json
  apps/www/src/__registry__/index.tsx
  apps/www/src/registry/default/plate-ui/combobox.tsx
  apps/www/src/registry/default/plate-ui/emoji-dropdown-menu.tsx
  apps/www/src/registry/default/plate-ui/emoji-toolbar-dropdown.tsx
  apps/www/src/registry/default/plate-ui/image-element.tsx
  apps/www/src/registry/default/plate-ui/media-embed-element.tsx
  apps/www/src/registry/default/plate-ui/media-floating-toolbar.tsx
  apps/www/src/registry/default/plate-ui/media-popover.tsx
  apps/www/src/registry/default/plate-ui/popover.tsx
  apps/www/src/registry/registry.ts
  config/eslint/bases/react.cjs
  packages/combobox/package.json
  packages/combobox/src/combobox.store.ts
  packages/combobox/src/hooks/useComboboxContent.ts
  packages/combobox/src/types/ComboboxProps.ts
  packages/emoji/src/hooks/useEmojiDropdownMenuState.ts
  packages/emoji/src/utils/EmojiPicker/useEmojiPicker.ts
  packages/floating/src/components/ElementPopover.tsx
  packages/floating/src/components/Popover.tsx
  packages/floating/src/components/index.ts
  packages/floating/src/hooks/index.ts
  packages/floating/src/hooks/useDropdownControls.ts
  packages/floating/src/index.ts
  packages/floating/src/utils/createVirtualRef.ts
  packages/floating/src/utils/getBoundingClientRect.ts
  packages/floating/src/utils/index.ts
  packages/floating/src/utils/makeClientRect.ts
  packages/floating/src/utils/mergeClientRects.spec.ts
  packages/floating/src/utils/mergeClientRects.ts
  packages/media/src/media/FloatingMedia/FloatingMediaUrlInput.tsx
  packages/plate-utils/src/hooks/index.ts
  packages/plate-utils/src/hooks/useStableMemo.ts
  yarn.lock
Labels: large

#2464 Add `editorRef` prop and new editor methods
  .changeset/clean-hotels-joke.md
  packages/core/src/components/EditorMethodsEffect.ts
  packages/core/src/components/EditorRefEffect.tsx
  packages/core/src/components/PlateEditable.tsx
  packages/core/src/components/PlateProvider.tsx
  packages/core/src/components/index.ts
  packages/core/src/hooks/usePlateEffects.ts
  packages/core/src/plugins/withPlate.ts
  packages/core/src/stores/plate/createPlateStore.ts
  packages/core/src/types/PlateEditor.ts
  packages/core/src/types/PlateEditorMethods.ts
  packages/core/src/types/PlateStore.ts
  packages/core/src/types/index.ts
  packages/suggestion/src/transforms/addSuggestionMark.spec.tsx
  packages/suggestion/src/withSuggestion.spec.tsx
Labels: medium, waiting-for-review

#2468 Add and update docs
  apps/www/content/docs/accessing-editor.mdx
  apps/www/content/docs/components/installation/next.mdx
  apps/www/content/docs/plugin-component.mdx
  apps/www/content/docs/plugin-components.mdx
  apps/www/content/docs/plugin.mdx
  apps/www/src/config/docs.ts
Labels: large, waiting-for-review

#2483 Fix typos in docs
  apps/www/content/docs/plugin.mdx
Labels: docs, small, waiting-for-review

#2486 Icon docs
  apps/www/content/docs/components/cli.mdx
  apps/www/content/docs/components/installation/manual.mdx
  apps/www/content/docs/components/installation/next.mdx
  apps/www/content/docs/components/installation/remix.mdx
  apps/www/content/docs/components/installation/vite.mdx
Labels: docs, small, waiting-for-review

#2499 Fix double quotes in cli
  .changeset/heavy-mugs-fix.md
  packages/cli/src/utils/transformers/index.ts
  packages/cli/src/utils/transformers/transform-css-vars.ts
  packages/cli/src/utils/transformers/transform-rsc.ts
  packages/cli/test/fixtures/next-src/next.config.js
  packages/cli/test/fixtures/next-src/tailwind.config.js
  packages/cli/test/fixtures/next/next.config.js
  packages/cli/test/fixtures/next/tailwind.config.js
  packages/cli/test/fixtures/t3-app/.eslintrc.cjs
  packages/cli/test/fixtures/t3-app/next.config.mjs
  packages/cli/test/fixtures/t3-app/src/env.mjs
  packages/cli/test/fixtures/t3-app/src/pages/_app.tsx
  packages/cli/test/fixtures/t3-app/src/pages/index.tsx
  packages/cli/test/fixtures/t3-app/tailwind.config.ts
  packages/cli/test/utils/__snapshots__/transform-css-vars.test.ts.snap
  packages/cli/test/utils/__snapshots__/transform-rsc.test.ts.snap
  packages/cli/test/utils/apply-color-mapping.test.ts
  packages/cli/test/utils/get-config.test.ts
  packages/cli/test/utils/get-package-manager.test.ts
  packages/cli/test/utils/registry.test.ts
  packages/cli/test/utils/resolve-import.test.ts
  packages/cli/test/utils/transform-css-vars.test.ts
  packages/cli/test/utils/transform-import.test.ts
  packages/cli/test/utils/transform-rsc.test.ts
Labels: large, waiting-for-review

#2500 Version Packages
  .changeset/heavy-mugs-fix.md
  packages/cli/CHANGELOG.md
  packages/cli/package.json
Labels: small, waiting-for-review

#2514 API Plugin docs
  .changeset/few-coins-drum.md
  apps/www/content/docs/alignment.mdx
  apps/www/content/docs/api/core.mdx
  apps/www/content/docs/api/core/plate.mdx
  apps/www/content/docs/api/core/store.mdx
  apps/www/content/docs/autoformat.mdx
  apps/www/content/docs/basic-elements.mdx
  apps/www/content/docs/basic-marks.mdx
  apps/www/content/docs/block-selection.mdx
  apps/www/content/docs/cloud.mdx
  apps/www/content/docs/combobox.mdx
  apps/www/content/docs/comments.mdx
  apps/www/content/docs/components/list-element.mdx
  apps/www/content/docs/dnd.mdx
  apps/www/content/docs/emoji.mdx
  apps/www/content/docs/excalidraw.mdx
  apps/www/content/docs/exit-break.mdx
  apps/www/content/docs/font.mdx
  apps/www/content/docs/highlight.mdx
  apps/www/content/docs/indent-list.mdx
  apps/www/content/docs/indent.mdx
  apps/www/content/docs/line-height.mdx
  apps/www/content/docs/link.mdx
  apps/www/content/docs/list.mdx
  apps/www/content/docs/media.mdx
  apps/www/content/docs/mention.mdx
  apps/www/content/docs/reset-node.mdx
  apps/www/content/docs/serializing-csv.mdx
  apps/www/content/docs/serializing-html.mdx
  apps/www/content/docs/serializing-md.mdx
  apps/www/content/docs/soft-break.mdx
  apps/www/content/docs/tabbable.mdx
  apps/www/content/docs/table.mdx
  apps/www/public/registry/styles/default/excalidraw-element.json
  apps/www/src/components/api-list.tsx
  apps/www/src/components/mdx-components.tsx
  apps/www/src/lib/plate/demo/plugins/autoformatBlocks.ts
  apps/www/src/lib/plate/demo/plugins/autoformatIndentLists.ts
  apps/www/src/lib/plate/demo/plugins/autoformatLists.ts
  apps/www/src/lib/plate/demo/plugins/autoformatMarks.ts
  apps/www/src/lib/plate/demo/plugins/autoformatPlugin.ts
  apps/www/src/lib/plate/demo/plugins/autoformatRules.ts
  apps/www/src/lib/plate/demo/plugins/autoformatUtils.ts
  apps/www/src/registry/default/example/playground-demo.tsx
  apps/www/src/registry/default/plate-ui/excalidraw-element.tsx
  package.json
  packages/excalidraw/CHANGELOG.md
  packages/excalidraw/src/hooks/index.ts
  packages/excalidraw/src/hooks/useExcalidrawElement.ts
  templates/plate-playground-template/src/components/plate-ui/excalidraw-element.tsx
  templates/plate-template/package.json
  yarn.lock
Labels: large, waiting-for-review

#2516 Version Packages
  .changeset/few-coins-drum.md
  packages/excalidraw/CHANGELOG.md
  packages/excalidraw/package.json
Labels: small, waiting-for-review

#2518 Remove comment node when new comment form is closed
  .changeset/empty-mails-sip.md
  packages/comments/src/components/useCommentLeaf.ts
Labels: small, waiting-for-review

#2519 Pass required values to `CommentsProvider` in template
  apps/www/content/docs/components/comments-popover.mdx
  templates/plate-playground-template/src/components/plate/editor.tsx
  templates/plate-playground-template/src/lib/plate/comments.ts
Labels: small, waiting-for-review

#2521 Version Packages
  .changeset/empty-mails-sip.md
  .changeset/modern-schools-worry.md
  .changeset/quiet-ghosts-invite.md
  packages/comments/CHANGELOG.md
  packages/comments/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/yjs/CHANGELOG.md
  packages/yjs/package.json
Labels: small, waiting-for-review

#2537 Use react-tweet for Tweets
  .changeset/large-boats-hang.md
  apps/www/package.json
  apps/www/src/registry/default/example/playground-demo.tsx
  apps/www/src/registry/default/plate-ui/image-element.tsx
  apps/www/src/registry/default/plate-ui/media-embed-element.tsx
  apps/www/src/registry/registry.ts
  packages/media/package.json
  packages/media/src/index.ts
  packages/media/src/media-embed/components/index.ts
  packages/media/src/media-embed/components/useMediaEmbed.ts
  packages/media/src/media-embed/createMediaEmbedPlugin.ts
  packages/media/src/media-embed/index.ts
  packages/media/src/media-embed/parseTwitterUrl.ts
  packages/media/src/media-embed/parseVideoUrl.ts
  packages/media/src/media/index.ts
  packages/media/src/media/mediaStore.ts
  packages/media/src/media/parseMediaUrl.ts
  packages/media/src/media/types.ts
  packages/media/src/media/useMediaState.ts
  packages/media/src/twitter/components/MediaEmbedTweet.tsx
  packages/media/src/twitter/components/Tweet.tsx
  packages/media/src/twitter/components/index.ts
  packages/media/src/twitter/index.ts
  packages/media/src/video/components/MediaEmbedVideo.tsx
  packages/media/src/video/components/index.ts
  packages/media/src/video/index.ts
  yarn.lock
Labels: large, waiting-for-review

#2540 Version Packages
  .changeset/caption.md
  .changeset/large-boats-hang.md
  .changeset/plate-res.md
  .changeset/tricky-donkeys-grab.md
  packages/caption/CHANGELOG.md
  packages/caption/package.json
  packages/media/CHANGELOG.md
  packages/media/package.json
  packages/mention/CHANGELOG.md
  packages/mention/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/resizable/CHANGELOG.md
  packages/resizable/package.json
  packages/serializer-csv/CHANGELOG.md
  packages/serializer-csv/package.json
  packages/serializer-docx/CHANGELOG.md
  packages/serializer-docx/package.json
  packages/table/CHANGELOG.md
  packages/table/package.json
Labels: medium, waiting-for-review

#2544 📝 Fix typo
  apps/www/content/docs/accessing-editor.mdx
Labels: docs, small, waiting-for-review
