Repository udecode/plate, pull requests merged in 2023-08, with the labels that each got.

#2549 Make contributing guide easier to find
  README.md
Labels: docs, small, waiting-for-review

#2553 Version Packages
  .changeset/odd-grapes-kneel.md
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializer-csv/CHANGELOG.md
  packages/serializer-csv/package.json
  packages/serializer-docx/CHANGELOG.md
  packages/serializer-docx/package.json
  packages/table/CHANGELOG.md
  packages/table/package.json
Labels: small, waiting-for-review

#2555 🐛 fix table resizable
  .changeset/olive-tips-marry.md
  .changeset/seven-trees-carry.md
  BREAKING_CHANGES.md
  apps/www/content/docs/table.mdx
  apps/www/public/registry/index.json
  apps/www/public/registry/styles/default/image-element.json
  apps/www/public/registry/styles/default/media-embed-element.json
  apps/www/public/registry/styles/default/resizable.json
  apps/www/public/registry/styles/default/table-cell-element.json
  apps/www/src/__registry__/index.tsx
  apps/www/src/registry/default/plate-ui/image-element.tsx
  apps/www/src/registry/default/plate-ui/media-embed-element.tsx
  apps/www/src/registry/default/plate-ui/resizable.tsx
  apps/www/src/registry/default/plate-ui/table-cell-element.tsx
  apps/www/src/registry/registry.ts
  packages/resizable/src/components/ResizeHandle.tsx
  packages/table/src/components/TableCellElement/index.ts
  packages/table/src/components/TableCellElement/useTableCellElementResizable.ts
Labels: large, waiting-for-review

#2557 Support table cell backround styles (2)
  .changeset/large-wasps-destroy.md
  .github/codesee-arch-diagram.yml
  apps/www/public/registry/styles/default/table-cell-element.json
  apps/www/src/registry/default/plate-ui/table-cell-element.tsx
  packages/serializer-docx/src/deserializer/__tests__/tables.spec.tsx
  packages/table/src/createTablePlugin.ts
  packages/table/src/types.ts
Labels: small, waiting-for-review

#2556 Version Packages
  .changeset/large-wasps-destroy.md
  .changeset/olive-tips-marry.md
  .changeset/seven-trees-carry.md
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/resizable/CHANGELOG.md
  packages/resizable/package.json
  packages/serializer-csv/CHANGELOG.md
  packages/serializer-csv/package.json
  packages/serializer-docx/CHANGELOG.md
  packages/serializer-docx/package.json
  packages/table/CHANGELOG.md
  packages/table/package.json
Labels: small, waiting-for-review

#2560 📚 docs: fix typo in accessing-editor.mdx
  apps/www/content/docs/accessing-editor.mdx
Labels: docs, small, waiting-for-review

#2559 [ListPlugin] Fix elements remove
  .changeset/violet-ravens-jam.md
  packages/list/src/deleteFragmentList.ts
Labels: small, waiting-for-review

#2562 [SelectOnBackspace] Remove empty node
  .changeset/six-trees-change.md
  packages/select/src/createSelectOnBackspacePlugin.ts
  packages/select/src/withSelectOnBackspace.ts
Labels: small, waiting-for-review

#2565 Version Packages
  .changeset/six-trees-change.md
  .changeset/violet-ravens-jam.md
  packages/indent-list/CHANGELOG.md
  packages/indent-list/package.json
  packages/list/CHANGELOG.md
  packages/list/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/select/CHANGELOG.md
  packages/select/package.json
  packages/serializer-docx/CHANGELOG.md
  packages/serializer-docx/package.json
  packages/serializer-md/CHANGELOG.md
  packages/serializer-md/package.json
Labels: small, waiting-for-review

#2564 add isMarkableVoid
  .changeset/orange-rules-enjoy.md
  .github/workflows/lint-typecheck.yml
  apps/www/content/docs/api/core/plate-plugin.mdx
  apps/www/src/registry/default/plate-ui/mention-element.tsx
  packages/core/src/plugins/createInlineVoidPlugin.ts
  packages/core/src/types/plugin/PlatePlugin.ts
  packages/mention/src/createMentionPlugin.ts
  packages/slate/src/interfaces/editor/index.ts
  packages/slate/src/interfaces/editor/isMarkableVoid.ts
  templates/plate-playground-template/src/components/plate-ui/mention-element.tsx
  yarn.lock
Labels: small, waiting-for-review

#2567 Version Packages
  .changeset/orange-rules-enjoy.md
  packages/plate/CHANGELOG.md
  packages/plate/package.json
Labels: small, waiting-for-review

#2571 🐛 markable void
  .changeset/green-avocados-kneel.md
  packages/core/src/plugins/createInlineVoidPlugin.ts
Labels: small

#2576 update react tweet to fix multi media styles
  apps/www/package.json
  yarn.lock
Labels: large

#2579 ✨ override node id
  .changeset/modern-panthers-smile.md
  .changeset/polite-rivers-chew.md
  packages/link/package.json
  packages/node-id/src/createNodeIdPlugin.spec.tsx
  packages/node-id/src/createNodeIdPlugin.ts
  packages/node-id/src/withNodeId.ts
  yarn.lock
Labels: medium

#2580 Version Packages
  .changeset/modern-panthers-smile.md
  .changeset/polite-rivers-chew.md
  packages/link/CHANGELOG.md
  packages/link/package.json
  packages/node-id/CHANGELOG.md
  packages/node-id/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializer-md/CHANGELOG.md
  packages/serializer-md/package.json
Labels: small

#2581 Modify insertTableRow and insertTableColumn to support header columns #2577
  .changeset/bright-dryers-suffer.md
  packages/table/src/transforms/insertTableColumn.ts
  packages/table/src/transforms/insertTableRow.ts
Labels: small

#2583 Version Packages
  .changeset/bright-dryers-suffer.md
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializer-csv/CHANGELOG.md
  packages/serializer-csv/package.json
  packages/serializer-docx/CHANGELOG.md
  packages/serializer-docx/package.json
  packages/table/CHANGELOG.md
  packages/table/package.json
Labels: small

#2585 🐛 Keep the floating toolbar in the viewport
  .changeset/violet-apricots-retursn.md
  .changeset/wet-ghosts-knock.md
  apps/www/content/docs/components/changelog.mdx
  apps/www/public/registry/styles/default/floating-toolbar.json
  apps/www/public/registry/styles/default/link-floating-toolbar.json
  apps/www/public/registry/styles/default/mention-element.json
  apps/www/src/config/docs.ts
  apps/www/src/registry/default/plate-ui/floating-toolbar.tsx
  apps/www/src/registry/default/plate-ui/link-floating-toolbar.tsx
  packages/floating/src/hooks/useFloatingToolbar.ts
  packages/link/src/components/FloatingLink/useFloatingLinkEdit.ts
  packages/link/src/components/FloatingLink/useFloatingLinkInsert.ts
  packages/link/src/components/FloatingLink/useVirtualFloatingLink.ts
Labels: large

#2586 Version Packages
  .changeset/violet-apricots-retursn.md
  .changeset/wet-ghosts-knock.md
  packages/floating/CHANGELOG.md
  packages/floating/package.json
  packages/link/CHANGELOG.md
  packages/link/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializer-md/CHANGELOG.md
  packages/serializer-md/package.json
Labels: small
