Repository udecode/plate, pull requests merged in 2023-11, with the labels that each got.

#2725 fix: Comments cannot be edited or deleted
  .changeset/long-poems-relax.md
  apps/www/src/registry/default/plate-ui/comment-more-dropdown.tsx
  apps/www/src/registry/default/plate-ui/comment-value.tsx
  packages/comments/src/components/index.ts
  packages/comments/src/components/useCommentValue.ts
Labels: small

#2726 Remove instruction to build registry from CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs, small

#2729 Parse white space according to the HTML spec
  .changeset/clean-sloths-draw.md
  .changeset/mighty-ties-rescue.md
  packages/core/src/plugins/html-deserializer/utils/collapse-white-space/collapseString.ts
  packages/core/src/plugins/html-deserializer/utils/collapse-white-space/collapseWhiteSpace.spec.ts
  packages/core/src/plugins/html-deserializer/utils/collapse-white-space/collapseWhiteSpace.ts
  packages/core/src/plugins/html-deserializer/utils/collapse-white-space/collapseWhiteSpaceChildren.ts
  packages/core/src/plugins/html-deserializer/utils/collapse-white-space/collapseWhiteSpaceElement.ts
  packages/core/src/plugins/html-deserializer/utils/collapse-white-space/collapseWhiteSpaceNode.ts
  packages/core/src/plugins/html-deserializer/utils/collapse-white-space/collapseWhiteSpaceText.ts
  packages/core/src/plugins/html-deserializer/utils/collapse-white-space/index.ts
  packages/core/src/plugins/html-deserializer/utils/collapse-white-space/inferWhiteSpaceRule.ts
  packages/core/src/plugins/html-deserializer/utils/collapse-white-space/isLastNonEmptyTextOfInlineFormattingContext.ts
  packages/core/src/plugins/html-deserializer/utils/collapse-white-space/stateTransforms.ts
  packages/core/src/plugins/html-deserializer/utils/collapse-white-space/types.ts
  packages/core/src/plugins/html-deserializer/utils/deserializeHtml.spec.tsx
  packages/core/src/plugins/html-deserializer/utils/deserializeHtml.ts
  packages/core/src/plugins/html-deserializer/utils/htmlStringToDOMNode.ts
  packages/core/src/plugins/html-deserializer/utils/htmlTextNodeToString.spec.ts
  packages/core/src/plugins/html-deserializer/utils/htmlTextNodeToString.ts
  packages/core/src/plugins/html-deserializer/utils/index.ts
  packages/core/src/plugins/html-deserializer/utils/inlineTagNames.ts
  packages/core/src/plugins/html-deserializer/utils/isHtmlBlockElement.ts
  packages/core/src/plugins/html-deserializer/utils/isHtmlInlineElement.ts
  packages/select/src/index.ts
  packages/serializer-docx/src/deserializer/__tests__/legal-in.spec.tsx
  packages/serializer-docx/src/deserializer/__tests__/legal.spec.tsx
  packages/serializer-docx/src/docx-cleaner/__tests__/output/brs.html
  packages/serializer-docx/src/docx-cleaner/__tests__/output/custom-style-reference.html
  packages/serializer-docx/src/docx-cleaner/__tests__/output/empty-paragraphs.html
  packages/serializer-docx/src/docx-cleaner/__tests__/output/nested-lists.html
  packages/serializer-docx/src/docx-cleaner/__tests__/output/whitespaces-1.html
  packages/serializer-docx/src/docx-cleaner/__tests__/output/whitespaces-2.html
  packages/serializer-docx/src/docx-cleaner/__tests__/output/whitespaces-3.html
  packages/serializer-docx/src/docx-cleaner/cleanDocx.spec.ts
  packages/serializer-docx/src/docx-cleaner/cleanDocx.ts
  packages/slate-utils/src/transforms/index.ts
Labels: large

#2735 Update changelog.mdx
  apps/www/content/docs/components/changelog.mdx
Labels: docs, small

#2733 [TablePlugin] Table cells merging
  .changeset/sixty-bats-explode.md
  .changeset/table.md
  apps/www/src/components/icons.tsx
  apps/www/src/lib/plate/demo/values/tableValue.tsx
  apps/www/src/registry/default/plate-ui/table-cell-element.tsx
  apps/www/src/registry/default/plate-ui/table-element.tsx
  packages/resizable/src/components/ResizeHandle.tsx
  packages/serializer-html/src/elementToHtml.ts
  packages/serializer-html/src/leafToHtml.ts
  packages/serializer-html/src/serializeHtml.ts
  packages/serializer-html/src/utils/createElementWithSlate.ts
  packages/table/src/components/TableCellElement/useTableCellElementResizable.ts
  packages/table/src/components/TableCellElement/useTableCellElementState.ts
  packages/table/src/components/TableElement/useSelectedCells.ts
  packages/table/src/components/TableElement/useTableElement.ts
  packages/table/src/constants.ts
  packages/table/src/createTablePlugin.ts
  packages/table/src/index.ts
  packages/table/src/merge/computeCellIndices.ts
  packages/table/src/merge/createEmptyCell.ts
  packages/table/src/merge/deleteColumn.ts
  packages/table/src/merge/deleteRow.ts
  packages/table/src/merge/findCellByIndexes.ts
  packages/table/src/merge/getCellIndices.ts
  packages/table/src/merge/getCellIndicesWithSpans.ts
  packages/table/src/merge/getCellPath.ts
  packages/table/src/merge/getTableGridByRange.ts
  packages/table/src/merge/index.ts
  packages/table/src/merge/insertTableColumn.ts
  packages/table/src/merge/insertTableRow.ts
  packages/table/src/merge/isTableRectangular.ts
  packages/table/src/merge/mergeTableCells.ts
  packages/table/src/merge/unmergeTableCells.ts
  packages/table/src/merge/useTableMergeState.ts
  packages/table/src/queries/getColSpan.ts
  packages/table/src/queries/getRowSpan.ts
  packages/table/src/queries/getTableGridAbove.ts
  packages/table/src/queries/getTableGridByRange.ts
  packages/table/src/stores/tableStore.ts
  packages/table/src/transforms/deleteColumn.ts
  packages/table/src/transforms/deleteRow.ts
  packages/table/src/transforms/insertTableColumn.ts
  packages/table/src/transforms/insertTableRow.spec.tsx
  packages/table/src/transforms/insertTableRow.ts
  packages/table/src/types.ts
  packages/table/src/utils/getEmptyCellNode.ts
  packages/table/src/utils/getEmptyRowNode.ts
  packages/table/src/withDeleteTable.spec.tsx
  yarn.lock
Labels: large

#2760 Use React context for controlled CommentsProvider values
  .changeset/grumpy-planes-attack.md
  apps/www/content/docs/comments.mdx
  apps/www/src/lib/plate/demo/comments/CommentsProvider.tsx
  apps/www/src/lib/plate/demo/values/tableValue.tsx
  packages/comments/src/stores/comments/CommentsProvider.tsx
Labels: medium

#2759 Version Packages
  .changeset/grumpy-planes-attack.md
  .changeset/sixty-bats-explode.md
  .changeset/table.md
  packages/comments/CHANGELOG.md
  packages/comments/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializer-csv/CHANGELOG.md
  packages/serializer-csv/package.json
  packages/serializer-docx/CHANGELOG.md
  packages/serializer-docx/package.json
  packages/serializer-html/CHANGELOG.md
  packages/serializer-html/package.json
  packages/table/CHANGELOG.md
  packages/table/package.json
Labels: small

#2768 Copy table bugfix
  .changeset/great-taxis-divide.md
  packages/table/src/withSetFragmentDataTable.ts
Labels: small

#2769 Version Packages
  .changeset/great-taxis-divide.md
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializer-csv/CHANGELOG.md
  packages/serializer-csv/package.json
  packages/serializer-docx/CHANGELOG.md
  packages/serializer-docx/package.json
  packages/table/CHANGELOG.md
  packages/table/package.json
Labels: small

#2771 Fix: insert table in paragraph
  .changeset/dirty-insects-obey.md
  packages/table/src/withInsertFragmentTable.ts
Labels: small

#2772 Version Packages
  .changeset/dirty-insects-obey.md
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializer-csv/CHANGELOG.md
  packages/serializer-csv/package.json
  packages/serializer-docx/CHANGELOG.md
  packages/serializer-docx/package.json
  packages/table/CHANGELOG.md
  packages/table/package.json
Labels: small

#2742 fix: ToolbarButton not update the pressed style
  apps/www/src/registry/default/plate-ui/toolbar.tsx
Labels: small

#2774 Version Packages
  .changeset/six-bears-destroy.md
  .changeset/strong-pants-rule.md
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializer-csv/CHANGELOG.md
  packages/serializer-csv/package.json
  packages/serializer-docx/CHANGELOG.md
  packages/serializer-docx/package.json
  packages/table/CHANGELOG.md
  packages/table/package.json
Labels: small

#2776 [Table] fix unmerge
  .changeset/slimy-suns-joke.md
  packages/table/src/merge/computeCellIndices.ts
  packages/table/src/merge/isTableRectangular.ts
  packages/table/src/merge/unmergeTableCells.ts
  packages/table/src/merge/useTableMergeState.ts
Labels: small

#2780 Version Packages
  .changeset/eighty-berries-study.md
  .changeset/slimy-suns-joke.md
  packages/floating/CHANGELOG.md
  packages/floating/package.json
  packages/link/CHANGELOG.md
  packages/link/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializer-csv/CHANGELOG.md
  packages/serializer-csv/package.json
  packages/serializer-docx/CHANGELOG.md
  packages/serializer-docx/package.json
  packages/serializer-md/CHANGELOG.md
  packages/serializer-md/package.json
  packages/table/CHANGELOG.md
  packages/table/package.json
Labels: small

#2781 Add changeset for resizable
  .changeset/tasty-kiwis-raise.md
Labels: small

#2783 Version Packages
  .changeset/tasty-kiwis-raise.md
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/resizable/CHANGELOG.md
  packages/resizable/package.json
  packages/serializer-csv/CHANGELOG.md
  packages/serializer-csv/package.json
  packages/serializer-docx/CHANGELOG.md
  packages/serializer-docx/package.json
  packages/table/CHANGELOG.md
  packages/table/package.json
Labels: small
