Repository udecode/plate, pull requests merged in 2023-06, with the labels that each got.

#2421 fix: improve emoji plugin
  .changeset/emoji-plugin.md
  packages/nodes/emoji/src/handlers/getFindTriggeringInput.ts
  packages/nodes/emoji/src/utils/EmojiTriggeringController.ts
  packages/nodes/emoji/src/utils/EmojiTriggeringController.types.ts
  packages/nodes/emoji/src/utils/IndexSearch/IndexSearch.ts
  packages/nodes/emoji/src/withEmoji.ts
Labels: small, waiting-for-review

#2422 Version Packages
  .changeset/emoji-plugin.md
  packages/headless/CHANGELOG.md
  packages/headless/package.json
  packages/nodes/emoji/CHANGELOG.md
  packages/nodes/emoji/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/ui/nodes/emoji/CHANGELOG.md
  packages/ui/nodes/emoji/package.json
  packages/ui/plate/CHANGELOG.md
  packages/ui/plate/package.json
Labels: small, waiting-for-review

#2425 Feat/add touch event to resizable
  .changeset/hot-teachers-complain.md
  config/aliases-plate.js
  packages/resizable/src/components/ResizeHandle.tsx
  packages/resizable/src/utils/index.ts
  packages/resizable/src/utils/isTouchEvent.ts
Labels: small, waiting-for-review

#2430 fix: mentions trigger
  .changeset/spicy-monkeys-relax.md
  packages/nodes/mention/src/withMention.spec.tsx
  packages/nodes/mention/src/withMention.ts
Labels: small, waiting-for-review

#2433 fix: emoji plugin
  .changeset/spicy-ramen.md
  packages/nodes/emoji/src/constants.ts
  packages/nodes/emoji/src/createEmojiPlugin.ts
  packages/nodes/emoji/src/handlers/getEmojiOnSelectItem.ts
  packages/nodes/emoji/src/handlers/getFindTriggeringInput.ts
  packages/nodes/emoji/src/types.ts
  packages/nodes/emoji/src/utils/EmojiTriggeringController.ts
  packages/nodes/emoji/src/utils/EmojiTriggeringController.types.ts
  packages/nodes/emoji/src/utils/IndexSearch/IndexSearch.ts
  packages/nodes/emoji/src/withEmoji.ts
Labels: medium, waiting-for-review

#2435 Fix comment popover button icons
  .changeset/nasty-terms-heal.md
  .changeset/weak-ways-impress.md
  packages/ui/button/src/Button/PlateButton.tsx
  packages/ui/button/src/Button/RemoveNodeButton.tsx
  packages/ui/nodes/table/src/PlateTableBordersDropdownMenuContent.tsx
  packages/ui/nodes/table/src/PlateTablePopover.tsx
Labels: small, waiting-for-review

#2441 Added option to skip link sanitation
  .changeset/silly-mugs-care.md
  docs/docs/plugins/link.mdx
  packages/nodes/link/src/createLinkPlugin.ts
  packages/nodes/link/src/utils/getLinkAttributes.spec.ts
  packages/nodes/link/src/utils/getLinkAttributes.ts
  packages/nodes/link/src/utils/validateUrl.ts
Labels: small, waiting-for-review

#2443 Version Packages
  .changeset/silly-mugs-care.md
  packages/headless/CHANGELOG.md
  packages/headless/package.json
  packages/nodes/link/CHANGELOG.md
  packages/nodes/link/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializers/md/CHANGELOG.md
  packages/serializers/md/package.json
  packages/ui/nodes/link/CHANGELOG.md
  packages/ui/nodes/link/package.json
  packages/ui/nodes/media/CHANGELOG.md
  packages/ui/nodes/media/package.json
  packages/ui/plate/CHANGELOG.md
  packages/ui/plate/package.json
Labels: small, waiting-for-review

#2439 Plate UI tw mobile toolbar
  apps/www/src/components/plate-ui/fixed-toolbar-buttons.tsx
  apps/www/src/components/plate-ui/fixed-toolbar.tsx
  apps/www/src/components/plate-ui/turn-into-dropdown-menu.tsx
  apps/www/src/components/ui/toolbar.tsx
  apps/www/src/components/ui/tooltip.tsx
Labels: medium, waiting-for-review

#2444 [LinkPlugin] Allows pasting `email` links from clipboard
  .changeset/smooth-beds-kneel.md
  packages/utils/src/isUrl.spec.ts
  packages/utils/src/isUrl.ts
  yarn.lock
Labels: small, waiting-for-review

#2448 [ImageElement] Fix image caption width
  .changeset/fifty-kids-raise.md
  packages/ui/nodes/media/src/ImageElement/ImageElement.styles.ts
Labels: small, waiting-for-review

#2453 [LinkPlugin] Allow pasting links as urls
  .changeset/poor-ears-exercise.md
  packages/nodes/link/src/createLinkPlugin.ts
  packages/nodes/link/src/withLink.spec.tsx
  packages/nodes/link/src/withLink.ts
Labels: small, waiting-for-review

#2454 [HtmlDeserializer] Fix pasting tables with empty cells
  .changeset/funny-plants-listen.md
  packages/core/src/plugins/html-deserializer/utils/cleanHtmlEmptyElements.ts
Labels: small, waiting-for-review

#2450 Debug/serialize html/expected drag drop context
  .changeset/good-owls-jam.md
  docs/docs/plugins/SerializingHtmlSandpack.tsx
  docs/docs/sandpack/files/code-SerializingHtmlApp.tsx
  examples/src/SerializingHtmlApp.tsx
  packages/serializers/html/src/elementToHtml.ts
  packages/serializers/html/src/serializeHtml.ts
  packages/serializers/html/src/utils/createElementWithSlate.ts
Labels: medium, waiting-for-review

#2455 [TablePlugin] Allow to copy content from single cell
  packages/nodes/table/src/withSetFragmentDataTable.ts
  yarn.lock
Labels: large, waiting-for-review

#2461 [Changeset] Add changeset for copy single cell content
  .changeset/thick-meals-melt.md
Labels: small, waiting-for-review

#2458 [HtmlDeserializer] Fix pasting tables into safari from docx
  packages/core/src/plugins/html-deserializer/utils/copyBlockMarksToSpanChild.ts
  packages/core/src/plugins/html-deserializer/utils/isHtmlTable.ts
Labels: small, waiting-for-review
