Repository udecode/plate, pull requests merged in 2023-04, with the labels that each got.

#2328 Adds optional ondrop handler to draggableProps
  .changeset/early-mayflies-build.md
  packages/dnd/src/components/useDraggableState.ts
  packages/dnd/src/hooks/useDndNode.ts
  packages/dnd/src/hooks/useDragNode.ts
  packages/dnd/src/hooks/useDropNode.ts
  packages/ui/dnd/src/PlateDraggable.tsx
Labels: small, waiting-for-review

#2337 Version Packages
  .changeset/early-mayflies-build.md
  .changeset/tasty-jokes-applaud.md
  packages/dnd/CHANGELOG.md
  packages/dnd/package.json
  packages/ui/cloud/CHANGELOG.md
  packages/ui/cloud/package.json
  packages/ui/dnd/CHANGELOG.md
  packages/ui/dnd/package.json
Labels: small, waiting-for-review

#2310 Plugin Docs
  docs/.yarn/install-state.gz
  docs/docs/components/balloon-toolbar.mdx
  docs/docs/components/cursor-overlay.mdx
  docs/docs/components/dnd.mdx
  docs/docs/components/placeholder.mdx
  docs/docs/components/plate.mdx
  docs/docs/plugins/alignment.mdx
  docs/docs/plugins/autoformat.mdx
  docs/docs/plugins/basic-elements.mdx
  docs/docs/plugins/basic-marks.mdx
  docs/docs/plugins/block-selection.mdx
  docs/docs/plugins/combobox.mdx
  docs/docs/plugins/comments.mdx
  docs/docs/plugins/emoji.mdx
  docs/docs/plugins/excalidraw.mdx
  docs/docs/plugins/exit-break.mdx
  docs/docs/plugins/find-replace.mdx
  docs/docs/plugins/font.mdx
  docs/docs/plugins/forced-layout.mdx
  docs/docs/plugins/highlight.mdx
  docs/docs/plugins/horizontal-rule.mdx
  docs/docs/plugins/indent-list.mdx
  docs/docs/plugins/indent.mdx
  docs/docs/plugins/kbd.mdx
  docs/docs/plugins/line-height.mdx
  docs/docs/plugins/link.mdx
  docs/docs/plugins/list.mdx
  docs/docs/plugins/media.mdx
  docs/docs/plugins/mention.mdx
  docs/docs/plugins/reset-node.mdx
  docs/docs/plugins/serializing-csv.mdx
  docs/docs/plugins/serializing-docx.mdx
  docs/docs/plugins/serializing-html.mdx
  docs/docs/plugins/serializing-md.mdx
  docs/docs/plugins/single-line.mdx
  docs/docs/plugins/soft-break.mdx
  docs/docs/plugins/tabbable.mdx
  docs/docs/plugins/table.mdx
  docs/docs/sandpack/files/code-LinkApp.tsx
  examples/apps/e2e-examples/tsconfig.node.tsbuildinfo
  examples/src/placeholder/withStyledPlaceHolders.ts
Labels: large, waiting-for-review

#2317 Get right mention input type when overriden
  .changeset/tricky-garlics-guess.md
  packages/nodes/mention/src/getMentionOnSelectItem.ts
Labels: small

#2346 Version Packages
  .changeset/tricky-garlics-guess.md
  packages/headless/CHANGELOG.md
  packages/headless/package.json
  packages/nodes/mention/CHANGELOG.md
  packages/nodes/mention/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/ui/nodes/mention/CHANGELOG.md
  packages/ui/nodes/mention/package.json
  packages/ui/plate/CHANGELOG.md
  packages/ui/plate/package.json
Labels: small, waiting-for-review

#2351 Todo list line break issue fix
  .changeset/unlucky-hounds-cover.md
  docs/.yarn/install-state.gz
  docs/docs/plugins/list.mdx
  packages/nodes/list/src/insertBreakTodoList.ts
  packages/nodes/list/src/queries/getTodoListItemEntry.ts
  packages/nodes/list/src/todo-list/createTodoListPlugin.ts
  packages/nodes/list/src/transforms/insertTodoListItem.ts
  packages/nodes/list/src/types.ts
  packages/nodes/list/src/withTodoList.ts
  yarn.lock
Labels: medium, waiting-for-review

#2354 fix: add delay to DnD scroller
  .changeset/blue-cats-wave.md
  packages/dnd/src/components/Scroller/DndScroller.tsx
Labels: small, waiting-for-review

#2356 Revert "fix: add delay to DnD scroller"
  .changeset/blue-cats-wave.md
  packages/dnd/src/components/Scroller/DndScroller.tsx
Labels: small, waiting-for-review

#2358 fix: add missing readOnly dep in useEditableProps
  .changeset/twelve-months-bow.md
  packages/core/src/hooks/useEditableProps.ts
Labels: small, waiting-for-review

#2359 🐛 trailing-block type
  .changeset/shaggy-ties-sin.md
  packages/editor/trailing-block/src/withTrailingBlock.ts
Labels: small, waiting-for-review

#2360 Version Packages
  .changeset/shaggy-ties-sin.md
  packages/editor/trailing-block/CHANGELOG.md
  packages/editor/trailing-block/package.json
  packages/headless/CHANGELOG.md
  packages/headless/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/ui/plate/CHANGELOG.md
  packages/ui/plate/package.json
Labels: small, waiting-for-review

#2366 Fix media insertData
  .changeset/old-books-deliver.md
  packages/media/src/image/withImageUpload.ts
  packages/media/src/video/parseVideoUrl.ts
Labels: small, waiting-for-review

#2368 🐛 Fix test
  .changeset/tame-chicken-bake.md
  packages/core/src/plugins/createDeserializeAstPlugin.ts
Labels: small, waiting-for-review

#2375 Version Packages
  .changeset/friendly-roses-glow.md
  packages/headless/CHANGELOG.md
  packages/headless/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializers/csv/CHANGELOG.md
  packages/serializers/csv/package.json
  packages/ui/plate/CHANGELOG.md
  packages/ui/plate/package.json
Labels: small, waiting-for-review
