Repository udecode/plate, pull requests merged in 2023-05, with the labels that each got.

#2357 fix: add delay to DnD scroller
  .changeset/blue-cats-wave.md
  packages/dnd/src/components/Scroller/DndScroller.tsx
Labels: small, waiting-for-review

#2380 Version Packages
  .changeset/blue-cats-wave.md
  packages/dnd/CHANGELOG.md
  packages/dnd/package.json
  packages/ui/dnd/CHANGELOG.md
  packages/ui/dnd/package.json
Labels: small, waiting-for-review

#2382 🐛 open dropdown
  .changeset/dull-doors-taste.md
  packages/ui/toolbar/src/ToolbarDropdown/useDropdownControls.ts
Labels: small, waiting-for-review

#2383 Version Packages
  .changeset/dull-doors-taste.md
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/ui/comments/CHANGELOG.md
  packages/ui/comments/package.json
  packages/ui/find-replace/CHANGELOG.md
  packages/ui/find-replace/package.json
  packages/ui/nodes/alignment/CHANGELOG.md
  packages/ui/nodes/alignment/package.json
  packages/ui/nodes/code-block/CHANGELOG.md
  packages/ui/nodes/code-block/package.json
  packages/ui/nodes/emoji/CHANGELOG.md
  packages/ui/nodes/emoji/package.json
  packages/ui/nodes/excalidraw/CHANGELOG.md
  packages/ui/nodes/excalidraw/package.json
  packages/ui/nodes/font/CHANGELOG.md
  packages/ui/nodes/font/package.json
  packages/ui/nodes/line-height/CHANGELOG.md
  packages/ui/nodes/line-height/package.json
  packages/ui/nodes/link/CHANGELOG.md
  packages/ui/nodes/link/package.json
  packages/ui/nodes/list/CHANGELOG.md
  packages/ui/nodes/list/package.json
  packages/ui/nodes/media/CHANGELOG.md
  packages/ui/nodes/media/package.json
  packages/ui/nodes/table/CHANGELOG.md
  packages/ui/nodes/table/package.json
  packages/ui/plate/CHANGELOG.md
  packages/ui/plate/package.json
  packages/ui/suggestion/CHANGELOG.md
  packages/ui/suggestion/package.json
  packages/ui/toolbar/CHANGELOG.md
  packages/ui/toolbar/package.json
Labels: medium, waiting-for-review

#2386 Version Packages
  .changeset/soft-peaches-lick.md
  packages/selection/CHANGELOG.md
  packages/selection/package.json
Labels: small, waiting-for-review

#2388 Dropdown Floating toolbar is closing
  packages/nodes/emoji/src/utils/EmojiObserver.ts
  packages/ui/toolbar/src/BalloonToolbar/BalloonToolbar.tsx
  packages/ui/toolbar/src/BalloonToolbar/BalloonToolbar.types.ts
  packages/ui/toolbar/src/BalloonToolbar/useFloatingToolbar.ts
Labels: small, waiting-for-review

#2393 Added changeset
  .changeset/balloon-toolbar.md
Labels: small, waiting-for-review

#2394 Version Packages
  .changeset/balloon-toolbar.md
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/ui/comments/CHANGELOG.md
  packages/ui/comments/package.json
  packages/ui/find-replace/CHANGELOG.md
  packages/ui/find-replace/package.json
  packages/ui/nodes/alignment/CHANGELOG.md
  packages/ui/nodes/alignment/package.json
  packages/ui/nodes/code-block/CHANGELOG.md
  packages/ui/nodes/code-block/package.json
  packages/ui/nodes/emoji/CHANGELOG.md
  packages/ui/nodes/emoji/package.json
  packages/ui/nodes/excalidraw/CHANGELOG.md
  packages/ui/nodes/excalidraw/package.json
  packages/ui/nodes/font/CHANGELOG.md
  packages/ui/nodes/font/package.json
  packages/ui/nodes/line-height/CHANGELOG.md
  packages/ui/nodes/line-height/package.json
  packages/ui/nodes/link/CHANGELOG.md
  packages/ui/nodes/link/package.json
  packages/ui/nodes/list/CHANGELOG.md
  packages/ui/nodes/list/package.json
  packages/ui/nodes/media/CHANGELOG.md
  packages/ui/nodes/media/package.json
  packages/ui/nodes/table/CHANGELOG.md
  packages/ui/nodes/table/package.json
  packages/ui/plate/CHANGELOG.md
  packages/ui/plate/package.json
  packages/ui/suggestion/CHANGELOG.md
  packages/ui/suggestion/package.json
  packages/ui/toolbar/CHANGELOG.md
  packages/ui/toolbar/package.json
Labels: medium, waiting-for-review

#2400 Fix/2399 deserialize validAttribute nullcheck
  .changeset/large-trains-taste.md
  packages/core/src/plugins/html-deserializer/utils/pluginDeserializeHtml.spec.ts
  packages/core/src/plugins/html-deserializer/utils/pluginDeserializeHtml.ts
Labels: small, waiting-for-review

#2405 Make it possible to override link targets
  .changeset/afraid-pandas-argue.md
  docs/docs/plugins/link.mdx
  examples/src/link/linkPlugin.tsx
  packages/nodes/link/src/createLinkPlugin.ts
  packages/nodes/link/src/utils/getLinkAttributes.spec.ts
  packages/nodes/link/src/utils/getLinkAttributes.ts
  packages/serializers/html/src/__tests__/node-to-props.spec.ts
  packages/serializers/html/src/__tests__/with-attributes.spec.ts
Labels: small, waiting-for-review

#2406 Version Packages
  .changeset/afraid-pandas-argue.md
  packages/headless/CHANGELOG.md
  packages/headless/package.json
  packages/nodes/link/CHANGELOG.md
  packages/nodes/link/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializers/md/CHANGELOG.md
  packages/serializers/md/package.json
  packages/ui/nodes/link/CHANGELOG.md
  packages/ui/nodes/link/package.json
  packages/ui/nodes/media/CHANGELOG.md
  packages/ui/nodes/media/package.json
  packages/ui/plate/CHANGELOG.md
  packages/ui/plate/package.json
Labels: small, waiting-for-review

#2379 fixes doc links to combobox
  docs/docs/plugins/emoji.mdx
  docs/docs/plugins/mention.mdx
Labels: docs, small, waiting-for-review

#2392 Correct docs on serializing HTML without editor instance
  docs/docs/plugins/serializing-html.mdx
Labels: docs, small, waiting-for-review

#2412 🐛 suggestion imports
  .changeset/popular-waves-relax.md
  packages/suggestion/src/transforms/acceptSuggestion.ts
  packages/suggestion/src/transforms/rejectSuggestion.ts
Labels: small, waiting-for-review

#2414 Version Packages
  .changeset/popular-waves-relax.md
  packages/headless/CHANGELOG.md
  packages/headless/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/suggestion/CHANGELOG.md
  packages/suggestion/package.json
  packages/ui/plate/CHANGELOG.md
  packages/ui/plate/package.json
Labels: small, waiting-for-review

#2415 fix: support slate 0.94.1 after changing prop name for value to initialValue
  .changeset/metal-toys-shop.md
  packages/core/src/hooks/useSlateProps.ts
Labels: small, waiting-for-review
