Repository udecode/plate, pull requests merged in 2023-10, with the labels that each got.

#2658 ⬆️ upgrade templates
  .github/ci-templates.yml
  .github/workflows/ci-templates.yml
  apps/www/.gitignore
  apps/www/content/docs/api/core.mdx
  apps/www/src/app/_components/installation-tab.tsx
  apps/www/src/lib/plate/demo/plugins/TabbableElement.tsx
  apps/www/src/lib/plate/demo/plugins/alignPlugin.ts
  apps/www/src/lib/plate/demo/plugins/autoformatPlugin.ts
  apps/www/src/lib/plate/demo/plugins/basicElementsPlugins.ts
  apps/www/src/lib/plate/demo/plugins/basicMarksPlugins.ts
  apps/www/src/lib/plate/demo/plugins/basicNodesPlugins.ts
  apps/www/src/lib/plate/demo/plugins/captionPlugin.ts
  apps/www/src/lib/plate/demo/plugins/dragOverCursorPlugin.ts
  apps/www/src/lib/plate/demo/plugins/emojiPlugin.ts
  apps/www/src/lib/plate/demo/plugins/exitBreakPlugin.ts
  apps/www/src/lib/plate/demo/plugins/forcedLayoutPlugin.ts
  apps/www/src/lib/plate/demo/plugins/imagePlugins.ts
  apps/www/src/lib/plate/demo/plugins/indentListPlugin.ts
  apps/www/src/lib/plate/demo/plugins/lineHeightPlugin.ts
  apps/www/src/lib/plate/demo/plugins/linkPlugin.ts
  apps/www/src/lib/plate/demo/plugins/resetBlockTypePlugin.ts
  apps/www/src/lib/plate/demo/plugins/selectOnBackspacePlugin.ts
  apps/www/src/lib/plate/demo/plugins/softBreakPlugin.ts
  apps/www/src/lib/plate/demo/plugins/tabbablePlugin.ts
  apps/www/src/lib/plate/demo/plugins/trailingBlockPlugin.ts
  apps/www/src/lib/plate/demo/values/commentsValue.ts
  apps/www/src/lib/plate/demo/values/createHugeDocumentValue.tsx
  apps/www/src/lib/plate/demo/values/suggestionValue.ts
  apps/www/src/lib/plate/demo/values/usePlaygroundValue.ts
  apps/www/src/registry/default/example/cloud-demo.tsx
  apps/www/src/registry/default/example/editable-voids-demo.tsx
  apps/www/src/registry/default/example/editor-button.tsx
  apps/www/src/registry/default/example/editor-form.tsx
  apps/www/src/registry/default/example/editor-ghost.tsx
  apps/www/src/registry/default/example/editor-label.tsx
  apps/www/src/registry/default/example/editor-text.tsx
  apps/www/src/registry/default/example/find-replace-demo.tsx
  apps/www/src/registry/default/example/hundreds-blocks-demo.tsx
  apps/www/src/registry/default/example/hundreds-editors-demo.tsx
  apps/www/src/registry/default/example/iframe-demo.tsx
  apps/www/src/registry/default/example/multiple-editors-demo.tsx
  apps/www/src/registry/default/example/playground-demo.tsx
  apps/www/src/registry/default/example/preview-md-demo.tsx
  apps/www/src/types/plate-types.ts
  apps/www/tsconfig.tsbuildinfo
  config/eslint/bases/next.cjs
  config/tsup.config.ts
  package.json
  packages/code-block/src/decorateCodeLine.ts
  packages/core/src/hooks/usePlateEffects.ts
  packages/core/src/types/plugin/PlatePlugin.ts
  packages/core/src/utils/createPlateEditor.ts
  packages/core/src/utils/createPlugins.tsx
  templates/plate-playground-template/package.json
  templates/plate-playground-template/pnpm-lock.yaml
  yarn.lock
Labels: large

#2664 Version Packages
  .changeset/quiet-owls-cheat.md
  packages/caption/CHANGELOG.md
  packages/caption/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializer-md/CHANGELOG.md
  packages/serializer-md/package.json
Labels: small

#2663 fix tsup bundling local package imported types
  apps/www/src/registry/default/example/playground-demo.tsx
  config/eslint/bases/next.cjs
  config/tsconfig.test.json
  config/tsup.config.ts
  jest.config.cjs
  packages/autoformat/src/__tests__/withAutoformat/block/blockquote.spec.tsx
  packages/autoformat/src/__tests__/withAutoformat/block/code-block.spec.tsx
  packages/autoformat/src/__tests__/withAutoformat/block/heading.spec.tsx
  packages/autoformat/src/__tests__/withAutoformat/block/list.spec.tsx
  packages/autoformat/src/__tests__/withAutoformat/block/preFormat.spec.tsx
  packages/autoformat/src/__tests__/withAutoformat/ignoreTrim.spec.tsx
  packages/autoformat/src/__tests__/withAutoformat/invalid.spec.tsx
  packages/autoformat/src/__tests__/withAutoformat/mark/bold.spec.tsx
  packages/autoformat/src/__tests__/withAutoformat/mark/code.spec.tsx
  packages/autoformat/src/__tests__/withAutoformat/mark/italic.spec.tsx
  packages/autoformat/src/__tests__/withAutoformat/mark/multiple-marks.spec.tsx
  packages/autoformat/src/__tests__/withAutoformat/mark/strikethrough.spec.tsx
  packages/autoformat/src/__tests__/withAutoformat/text.spec.tsx
  packages/serializer-html/src/__tests__/serializeHtml/classNames.spec.ts
  packages/serializer-html/src/__tests__/serializeHtml/elements.spec.ts
  packages/serializer-html/src/__tests__/serializeHtml/marks.spec.ts
  packages/serializer-html/src/__tests__/serializeHtml/node-to-props.spec.ts
  packages/serializer-html/src/__tests__/serializeHtml/nodes.spec.ts
  packages/serializer-html/src/__tests__/serializeHtml/plain-text.spec.ts
  packages/serializer-html/src/__tests__/serializeHtml/with-attributes.spec.ts
  packages/serializer-html/src/__tests__/serializeHtml/with-serialize.spec.ts
  packages/serializer-html/src/__tests__/serializeHtml/with-useEditor.spec.ts
  packages/serializer-html/src/__tests__/serializeHtml/without-deserialize.spec.ts
  packages/utils/src/types/AnyObject.ts
  templates/plate-playground-template/package.json
  templates/plate-playground-template/pnpm-lock.yaml
  templates/plate-playground-template/src/lib/plate/plate-types.ts
  tsconfig.json
  yarn.lock
Labels: large

#2665 Disable tabbable when editor is read-only
  .changeset/cuddly-toes-hang.md
  packages/tabbable/src/TabbableEffects.tsx
Labels: small

#2668 Version Packages
  .changeset/cuddly-toes-hang.md
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/tabbable/CHANGELOG.md
  packages/tabbable/package.json
Labels: small

#2669 Lodash ES
  .changeset/silly-terms-type.md
  config/tsup.config.ts
  jest.config.cjs
  package.json
  packages/autoformat/package.json
  packages/autoformat/src/transforms/autoformatBlock.ts
  packages/autoformat/src/transforms/autoformatMark.ts
  packages/autoformat/src/transforms/autoformatText.ts
  packages/autoformat/src/utils/getMatchRange.ts
  packages/comments/package.json
  packages/comments/src/queries/getCommentPosition.ts
  packages/core/package.json
  packages/core/src/components/Editor.spec.tsx
  packages/core/src/hooks/useEditableProps.ts
  packages/core/src/hooks/usePlateEffects.ts
  packages/core/src/plugins/html-deserializer/utils/pluginDeserializeHtml.ts
  packages/core/src/utils/createPlugins.tsx
  packages/core/src/utils/flattenDeepPlugins.ts
  packages/core/src/utils/getKeysByTypes.ts
  packages/core/src/utils/mergeDeepPlugins.ts
  packages/core/src/utils/mergeDeepToNodes.ts
  packages/core/src/utils/normalizeInitialValue.ts
  packages/core/src/utils/overridePluginsByKey.ts
  packages/dnd/package.json
  packages/dnd/src/components/Scroller/ScrollArea.tsx
  packages/font/package.json
  packages/font/src/hooks/useColorsCustom.ts
  packages/list/package.json
  packages/list/src/onKeyDownList.ts
  packages/node-id/package.json
  packages/node-id/src/withNodeId.ts
  packages/normalizers/package.json
  packages/normalizers/src/withRemoveEmptyNodes.ts
  packages/plate-utils/package.json
  packages/plate-utils/src/plate/onKeyDownToggleElement.ts
  packages/plate-utils/src/queries/isType.ts
  packages/plate-utils/src/utils/createNodesHOC.tsx
  packages/plate-utils/src/utils/defaultsDeepToNodes.ts
  packages/slate-utils/package.json
  packages/slate-utils/src/queries/getPointBeforeLocation.ts
  packages/slate-utils/src/queries/getPreviousSiblingNode.ts
  packages/slate-utils/src/queries/queryEditor.ts
  packages/slate-utils/src/transforms/removeMark.ts
  packages/slate-utils/src/transforms/setMarks.ts
  packages/slate-utils/src/transforms/toggleMark.ts
  packages/table/package.json
  packages/table/src/withInsertFragmentTable.ts
  yarn.lock
Labels: medium

#2671 Fix lodash import
  .changeset/four-hornets-decide.md
  apps/www/package.json
  jest.config.cjs
  package.json
  packages/autoformat/package.json
  packages/autoformat/src/transforms/autoformatBlock.ts
  packages/autoformat/src/transforms/autoformatMark.ts
  packages/autoformat/src/transforms/autoformatText.ts
  packages/autoformat/src/utils/getMatchRange.ts
  packages/comments/package.json
  packages/comments/src/queries/getCommentPosition.ts
  packages/core/package.json
  packages/core/src/components/Editor.spec.tsx
  packages/core/src/hooks/useEditableProps.ts
  packages/core/src/hooks/usePlateEffects.ts
  packages/core/src/plugins/html-deserializer/utils/pluginDeserializeHtml.ts
  packages/core/src/utils/createPlugins.tsx
  packages/core/src/utils/flattenDeepPlugins.ts
  packages/core/src/utils/getKeysByTypes.ts
  packages/core/src/utils/mergeDeepPlugins.ts
  packages/core/src/utils/mergeDeepToNodes.ts
  packages/core/src/utils/normalizeInitialValue.ts
  packages/core/src/utils/overridePluginsByKey.ts
  packages/dnd/package.json
  packages/dnd/src/components/Scroller/ScrollArea.tsx
  packages/font/package.json
  packages/font/src/hooks/useColorsCustom.ts
  packages/list/package.json
  packages/list/src/onKeyDownList.ts
  packages/node-id/package.json
  packages/node-id/src/withNodeId.ts
  packages/normalizers/package.json
  packages/normalizers/src/withRemoveEmptyNodes.ts
  packages/plate-utils/package.json
  packages/plate-utils/src/plate/onKeyDownToggleElement.ts
  packages/plate-utils/src/queries/isType.ts
  packages/plate-utils/src/utils/createNodesHOC.tsx
  packages/plate-utils/src/utils/defaultsDeepToNodes.ts
  packages/serializer-html/src/__tests__/serializeHtml/plain-text.spec.ts
  packages/slate-utils/package.json
  packages/slate-utils/src/queries/getPointBeforeLocation.ts
  packages/slate-utils/src/queries/getPreviousSiblingNode.ts
  packages/slate-utils/src/queries/queryEditor.ts
  packages/slate-utils/src/transforms/removeMark.ts
  packages/slate-utils/src/transforms/setMarks.ts
  packages/slate-utils/src/transforms/toggleMark.ts
  packages/table/package.json
  packages/table/src/withInsertFragmentTable.ts
  templates/plate-playground-template/package.json
  templates/plate-playground-template/patches/react-dnd@15.1.2.patch
  templates/plate-playground-template/pnpm-lock.yaml
  templates/plate-template/package.json
  templates/plate-template/patches/react-dnd@15.1.2.patch
  templates/plate-template/pnpm-lock.yaml
  yarn.lock
Labels: large

#2678 FIX #2677 : CommonJS validator import in cleanDocXImageElements
  .changeset/great-files-boil.md
  packages/serializer-docx/src/docx-cleaner/utils/cleanDocxImageElements.ts
Labels: small

#2680 Star on github
  apps/www/package.json
  apps/www/src/components/counting-numbers.tsx
  apps/www/src/components/site-header.tsx
  apps/www/src/components/star-on-github.tsx
  turbo.json
  yarn.lock
Labels: large

#2679 Version Packages
  .changeset/great-files-boil.md
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializer-docx/CHANGELOG.md
  packages/serializer-docx/package.json
Labels: small

#2682 fetch newCellChildren or allow it to be passed into insertTable
  .changeset/long-students-retire.md
  packages/table/src/transforms/insertTable.ts
Labels: small

#2684 Version Packages
  .changeset/long-students-retire.md
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializer-csv/CHANGELOG.md
  packages/serializer-csv/package.json
  packages/serializer-docx/CHANGELOG.md
  packages/serializer-docx/package.json
  packages/table/CHANGELOG.md
  packages/table/package.json
Labels: small

#2693 🐛 Fix token import
  .changeset/twenty-rockets-thank.md
  packages/code-block/src/decorateCodeLine.ts
Labels: small

#2694 Version Packages
  .changeset/twenty-rockets-thank.md
  packages/basic-elements/CHANGELOG.md
  packages/basic-elements/package.json
  packages/code-block/CHANGELOG.md
  packages/code-block/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializer-md/CHANGELOG.md
  packages/serializer-md/package.json
Labels: small

#2687 Delete forward on empty line before code block unwraps code line #2686
  .changeset/shy-billo-bagga.md
  apps/www/src/config/customizer-items.ts
  apps/www/src/config/customizer-list.ts
  apps/www/src/config/descriptions.ts
  apps/www/src/registry/default/example/playground-demo.tsx
  packages/select/src/createDeletePlugin.spec.tsx
  packages/select/src/createDeletePlugin.ts
  packages/select/src/index.ts
  packages/select/src/withDelete.ts
  packages/select/src/withSelectOnBackspace.ts
  packages/serializer-docx/src/docx-cleaner/utils/cleanDocxImageElements.ts
  templates/plate-playground-template/src/lib/plate/plate-plugins.ts
Labels: medium, 🙋 Bounty claim

#2696 Fix import papaparse
  .changeset/forty-apes-teach.md
  packages/serializer-csv/src/deserializer/types.ts
  packages/serializer-csv/src/deserializer/utils/deserializeCsv.ts
Labels: small

#2697 Version Packages
  .changeset/forty-apes-teach.md
  .changeset/shy-billo-bagga.md
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/select/CHANGELOG.md
  packages/select/package.json
  packages/serializer-csv/CHANGELOG.md
  packages/serializer-csv/package.json
Labels: small

#2705 Fix: "Cannot resolve a DOM node from Slate node" floating link case
  .changeset/fast-eggs-burn.md
  packages/link/src/transforms/submitFloatingLink.ts
Labels: small

#2706 Version Packages
  .changeset/fast-eggs-burn.md
  packages/link/CHANGELOG.md
  packages/link/package.json
  packages/plate/CHANGELOG.md
  packages/plate/package.json
  packages/serializer-md/CHANGELOG.md
  packages/serializer-md/package.json
Labels: small

#2708 Improve performance of placeholder and draggable HOCs
  .changeset/chilled-candles-hunt.md
  .changeset/new-coins-suffer.md
  apps/www/src/registry/default/plate-ui/draggable.tsx
  packages/dnd/src/components/useDraggable.ts
  packages/plate-utils/src/hooks/usePlaceholder.ts
Labels: small

#2712 Add `asChild` to the TooltipTrigger in ToolbarButton
  apps/www/src/registry/default/plate-ui/toolbar.tsx
Labels: small

#2717 fix name of the comments-popover component in the doc
  apps/www/content/docs/components/comments-popover.mdx
Labels: docs, small

#2719 Add `removeEmpty` option to `insertNodes`
  .changeset/tender-socks-dress.md
  .changeset/tiny-carpets-help.md
  packages/media/src/media/insertMedia.ts
  packages/slate/src/interfaces/transforms/insertNodes.ts
Labels: medium
